import I18nInitializer from "@/components/I18nInitializer";
import "./globals.css";


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body  >
        <I18nInitializer />
        {children}
      </body>
    </html>
  );
}
